lanche = ('hamburguer', 'suco', 'pizza', 'pudim')
print('print(lanche[2]) = ', lanche[2])
print('print(lanche[0:2]) = ', lanche[0:2])
print('print(lanche[1:]) = ', lanche[1:])
print('print((lanche[:2])) = ', lanche[:2])
print('print(lanche[-1]) = ', lanche[-1])
print('print(len(lanche)) = ', len(lanche))
for elemento in lanche:
    print('for elemento in lanche:')
    print('Para cada repetição do laço FOR, atualiza a variável "elemento" para', elemento)
print('for contador in range(0, len(lanche)):')
print('"print(print(contador) = , contador)"')
print('"print(print(lanche[contador]) = , lanche[contador])"')
for contador in range(0, len(lanche)):
    print('print(contador) = ', contador)
    print('print(lanche[contador]) = ', lanche[contador])
print('for posicao, comida in enumerate(lanche):')
print('print(f"Na posição {posicao} tem a comida {comida}.")')
for posicao, comida in enumerate(lanche):
    print(f'Na posição {posicao} tem a comida {comida}.')
print('print(sorted(lanche)) = ', sorted(lanche))

print('=' * 30)
print('Mais formas de trabalhar com tuplas')
print('=' * 30)
a = (2, 5, 4)
print('print(a) = ', a)
b = (5, 8, 1, 2)
print('print(b) =', b)
c = a + b
print('print(c) = ', c)
print('print(len(c)) = ', len(c))
print('print(c.count(5)) = ', c.count(5))
print('print(c.count(9)) = ', c.count(9))
print('print(c.index(8)) = ', c.index(8))  # index retorna somente a primeira posição do argumento indicado
pessoa = ('Gustavo', 39, 'M', 99.88)
print('Tuplas aceitam quaisquer tipos de dados')
print('print(pessoa)', pessoa)
del (pessoa)
print('del(tupla) apaga a tupla')
print(pessoa)
