frase = 'Curso em Vídeo Python'
print(frase.upper())
print(frase.lower())
print(len(frase))
divisao = frase.split()
print(divisao)
print(divisao[2][1])
print(frase.replace('Python', 'Android'))
print(frase.capitalize())
print(frase.find('o'))
print('o' in frase)
print('#'.join(frase))
